name: ufrgs-ia
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.0
  - pandas=2.3
  - matplotlib=3.10
  - seaborn=0.13
  - tensorflow=2.18
  - numba=0.61.2
  - ipykernel=6.30
  - jupyterlab=4.4
  - ruff=0.13.0
